"""'Init'

Revision ID: 6046c78e7d90
Revises: 
Create Date: 2022-09-05 08:03:57.055074

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6046c78e7d90'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('books',
        sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
        sa.Column('link', sa.String(length=512), nullable=False),
        sa.Column('title', sa.String(length=512), nullable=True),
        sa.Column('author', sa.String(length=128), nullable=True),
        sa.Column('avialability', sa.String(length=128), nullable=True),
        sa.Column('price', sa.Integer(), nullable=True),
        sa.Column('special_price', sa.Integer(), nullable=True),
        sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_books_link'), 'books', ['link'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_books_link'), table_name='books')
    op.drop_table('books')
    # ### end Alembic commands ###
