"""'Init'

Revision ID: fb4481e8d5b7
Revises: 
Create Date: 2022-08-26 22:18:55.565517

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fb4481e8d5b7'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('address',
        sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
        sa.Column('address', sa.String(length=512), nullable=True),
        sa.PrimaryKeyConstraint('id')
    )
    op.create_table('birthday',
        sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
        sa.Column('birthday', sa.Date(), nullable=True),
        sa.PrimaryKeyConstraint('id')
    )
    op.create_table('record',
        sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
        sa.Column('birthday_id', sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(['birthday_id'], ['birthday.id'], ),
        sa.PrimaryKeyConstraint('id')
    )
    op.create_table('emails',
        sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
        sa.Column('email', sa.String(length=320), nullable=True),
        sa.Column('record_id', sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(['record_id'], ['record.id'], ondelete='CASCADE'),
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint('email')
    )
    op.create_table('names',
        sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
        sa.Column('name', sa.String(length=56), nullable=False),
        sa.Column('record_id', sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(['record_id'], ['record.id'], ondelete='CASCADE'),
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint('name')
    )
    op.create_table('phones',
        sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
        sa.Column('phone', sa.String(length=20), nullable=True),
        sa.Column('record_id', sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(['record_id'], ['record.id'], ondelete='CASCADE'),
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint('phone')
    )
    op.create_table('record_address',
        sa.Column('address_id', sa.Integer(), nullable=False),
        sa.Column('record_id', sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(['address_id'], ['address.id'], ),
        sa.ForeignKeyConstraint(['record_id'], ['record.id'], ),
        sa.PrimaryKeyConstraint('address_id', 'record_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('record_address')
    op.drop_table('phones')
    op.drop_table('names')
    op.drop_table('emails')
    op.drop_table('record')
    op.drop_table('birthday')
    op.drop_table('address')
    # ### end Alembic commands ###
